# Sisipkan di vhost psimkg.bmkg.go.id SEBELUM ProxyPass / ke portal :3001

ProxyPass        /instrument/api/ http://127.0.0.1:8011/
ProxyPassReverse /instrument/api/ http://127.0.0.1:8011/
ProxyPass        /instrument      http://127.0.0.1:3011/instrument
ProxyPassReverse /instrument      http://127.0.0.1:3011/instrument
